In [11]:
import numpy as np

In [37]:
with open("input.txt") as f:
    text = f.read()
text_split = text.split('\n')[:-1]
text_split;

In [41]:
data = np.array([[int(i) for i in line] for line in text_split])
data_cons = np.array([[i for i in line[1:-1]] for line in data[1:-1]])

In [39]:
data[:2,4] > 0

array([False,  True])

### How many visible trees

In [53]:
count = 0
for i, row in enumerate(data_cons):
    i += 1
    for j, val in enumerate(row):
        j += 1
        left = data[i,:j]
        right = data[i,j+1:]
        top = [data[:i,j]]
        bottom = [data[i+1:, j]]
        if np.all(left < val) or np.all(top < val) or np.all(right < val) or np.all(bottom < val):
            count += 1

        if i == 5 and j == 6:
            print(left)
            print(top)
            print(val)

count

[1 0 2 0 2 3]
[array([3, 0, 3, 0, 2])]
3


1321

In [54]:
99*2 + 97*2 + 1321

1713

### Highest scenic score

In [79]:
def count_visible_trees(arr, val):
    score = 0
    # print(arr)
    for i in arr:
        # print()
        if i >= val:
            score += 1
            break
        score += 1
    return score

In [80]:
scenic_scores = []
for i, row in enumerate(data):
    for j, val in enumerate(row):
        left = data[i,:j]
        right = data[i,j+1:]
        top = data[:i,j]
        bottom = data[i+1:, j]

        score = 1
        for direction in [np.flip(left), right, np.flip(top), bottom]:
            score *= count_visible_trees(direction, val)
        scenic_scores.append(score)


In [81]:
np.max(scenic_scores)

268464

In [78]:
scenic_scores[-1]

4

In [57]:
a = np.array([1,2,3])

In [58]:
np.flip(a)

array([3, 2, 1])